name: Build and Deploy

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Or your preferred Node version

      - name: Install dependencies
        run: npm install

      - name: Build with esbuild
        run: npm run build  # This runs your esbuild command as defined in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static  # This should match your output folder
